image: maven:3-jdk-8

services:
  - postgres:latest

stages:
  - build
  - test
  - deploy

before_script:
  - chmod +x mvnw

unit_test:
  stage: test
  script:
    - mvn clean test -B

.build: &build_template
  stage: build
  script:
    - mvn package -B

develop_build:
  <<: *build_template
  only:
    - branches
  except:
    - master
    - dev
  artifacts:
    expire_in: 1 day
    paths:
      - target/*.jar

production:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG target/docker/
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - master
    - dev
