image: maven:latest

services:
  - postgres:latest

stages:
  - test
  - build
  - deploy

before_script:
  - cd backend

unit_test:
  stage: test
  script:
    - mvn test -B

build:
  stage: build
  script:
    - bash config.sh $GC_INSTANCE $GC_DB_NAME $DB_USER $DB_PASS
    - mvn package -B -Dmaven.test.skip=true -P release
  artifacts:
    expire_in: 1 days
    paths:
      - backend/target

deploy:
  stage: deploy
  only:
    - master
    - dev
  script:
    - echo "$GCLOUD_SERVICE_KEY" > ./gcloud-service-key.json
    - sed -i -e "s;eng-contact-261713;park-hub;g" pom.xml
    - mvn appengine:deploy -Dmaven.test.skip=true -DserviceAccountKeyFile=./gcloud-service-key.json -P release
  after_script:
    - rm ./gcloud-service-key.json
