runtime: java

handlers:
  - url: /.*
    script: this field is required, but ignored

includes:
  - env_variables.yaml

logging:
  level:
    ROOT: INFO
    log4j:
      rootLogger: INFO, STDOUT
      logger:
        deng: INFO
        appender:
          STDOUT: org.apache.log4j.ConsoleAppender
          log4j:
            appender:
              STDOUT:
                layout: org.apache.log4j.PatternLayout

runtime_config:   # Optional
  jdk: openjdk8
  server: jetty9
